language: node_js
sudo: false
addons:
  chrome: stable
node_js:
- '10'
cache: yarn
script:
- yarn run build
after_success:
- set -e
- openssl aes-256-cbc -K $encrypted_cbefc3e1ec6b_key -iv $encrypted_cbefc3e1ec6b_iv -in packaging-key.pem.enc -out packaging-key.pem -d
- google-chrome-stable --pack-extension=dist --pack-extension-key=packaging-key.pem
- mv dist.crx better-sms-${TRAVIS_COMMIT}.crx
deploy:
  provider: releases
  api_key:
    secure: laVZ12KIblCG+m2P+m7gbJh/1Sbt+4oixymyNetjJ35wVz7hh64hqGJyLkJKbsL13kHKtYrSgUcPhlJ3ehH6Hs9JQPPCX9uaIQfKgngMW6x/DqUc4gXgVeRbNXCinyfX4xCVzawFDRA30yGEUs816tUZTH9qa+3ze9Z0IvET/dgLOAMjwrfqtuaJ8cuX5fiV2ioTWgHv0ff0ZJP3BISgc/XXZFF6dLem6Q7DOO+EqBuVRFBBLZ67uccsm8qMRUAljTI3oP8E9vVye4Bwn5K33BrmiuOJeoR6yauKlgXo4wx6kRf2QPfTtzZKx+jr+TJwinRWy6I7ojCvdA9JWIu4/HEQWB4TK7BMHL4BLWET3oeLngpRhN8I6kozxVQMrbjrmXsuEirxy0yetP4X/MbrlHwDOYZ3h8OUM/rMeC1GfZWGLBWccnHLTfV77b94agiuNa1CujOofq3Leomou1wZKm5oZM2jwOTAql2yhbFHO4NMxUa2BaaijVn3eSnbxRTal1GttnknY8obeWiVJ0ozYtVnp2SVyHXUHOWtVYoY/YfmanJ6uwrLG8t+rMB2gpeE0reRBkgCt4pVdYuPd20HxHELTSMR9Dsoa4sGMTSw/tZOVO2xLXPhrckeZVpKNmJ6BPQRfOKayVtCNZfgwveSm4M8a1ui9Q/YOhfp4PU4U4U=
  file: better-sms-${TRAVIS_COMMIT}.crx
  skip_cleanup: true
  prerelease: true
