language: node_js
sudo: false
addons:
  chrome: stable
node_js:
- '10'
cache: yarn
script:
- yarn run build
after_success:
- set -e
- openssl aes-256-cbc -K $encrypted_0373efeb2806_key -iv $encrypted_0373efeb2806_iv -in packaging-key.pem.enc -out packaging-key.pem -d
- yarn run package:nightly
deploy:
  provider: releases
  api_key:
    secure: "MsAPDY4T0Rz7PxABHiQRPPt8pU0NFEXa2rjuDjgSkbmaX3k2mUi57Hh0AT3rUxyf3dB7Wc4N0FuKDY/JjStvzQyefcsbSh8XN8OsZTwfBUSsXvve4gWCcDbbaVZy68fXLljzXRvoFAnCCyFBXyZ6U88bj88146l5yy62a6vphDOjYY1bQ47GuppssjjpimxgKjasFdzWUGUFyTD72PjrCQ6nPC9Mq3N7ihuSdhgrO8XFP+6NTpm0UrA15d50/rPpRJd9KEelXfylwlXGjFbgOnF6Q89uNbq5bsZgWQ3Svf0vJeZjnkGBjSipH2zlHNg/cLQKea5cllWh88KH2eH81jog45/JZqr7fscrhEB8V+/dT83R8GDYu28ntupSIzHaPY3c1kRB6RmJkhtd+u/nkK/2MRKsUPnMmF1B1X+ImurQJ/dGIvcqAEFC6RlJhcdaN0VwFFwl5hFsJn0q3nAF2ulNdqxL/RQTAGbD3jpnaPQNBGpPJTMbMtrbHyVlXiAqh0KubYJ8i58dRR/LzlzmPAAtahXsTlNhvF3Ca6UDx2Rul4SSc250ilazxlawVkamS4PrWV+9KVTMipr6wd+bKsMKC7Aw5qZ7tpxoKiVc1m4KGQewSzcGsBwlZlzaaRVIh201p++oHTXvx9F6Wj0Hpvf8KePcPVBy6y04DT7ygMo="
  file: better-sms-${TRAVIS_COMMIT}.crx
  skip_cleanup: true
  prerelease: true
